name       : haskell-lexer
version    : '1.1'
release    : 3
source     :
    - https://hackage.haskell.org/package/haskell-lexer-1.1/haskell-lexer-1.1.tar.gz : 313a15cc643322c8badd148867ce25ca1ffc191df9e7eeec5b10bc08c4b563d5
license    : BSD-3-Clause
component  : programming.haskell
summary    : A fully compliant Haskell 98 lexer.
description: |
    A fully compliant Haskell 98 lexer.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
