name       : haskell-lexer
version    : 1.0.1
release    : 1
source     :
    - https://hackage.haskell.org/package/haskell-lexer-1.0.1/haskell-lexer-1.0.1.tar.gz : d7d42ab3c4bc2f0232ede8b005fb9de57f862ee4c1c83aa61e1022346fc84366
license    : BSD-3-Clause
component  : programming.haskell
summary    : A fully compliant Haskell 98 lexer.
description: |
    A fully compliant Haskell 98 lexer.
builddeps  :
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
